//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("PartyDisplay.Dolphin")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0+c8b22ee1f9195d0e56aabae54a3c52db6efbc3ef")]
[assembly: System.Reflection.AssemblyProductAttribute("PartyDisplay.Dolphin")]
[assembly: System.Reflection.AssemblyTitleAttribute("PartyDisplay.Dolphin")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform("windows")]
[assembly: System.Runtime.Versioning.SupportedOSPlatform("linux")]

// Generated by the MSBuild WriteCodeFragment class.

